### ISSUE TITLE
Domain knows about ASP.NET implementation

### ISSUE THREAD

**Issue by afgalvan** [cantte/Armory.Api#17]
# Domain knows about ASP.NET implementation

Correct me if I'm wrong, but the Domain layer shouldn't know about implementations, and by having the [Armory User](https://github.com/cantte/Armory.Api/blob/634eaa850054558ceab902a0d6dd476f44c0ead1/src/Armory/Users/Domain/ArmoryUser.cs) in that layer, he knows he's implementing the IdentityUser from the AspNetCore library.

**Comment by cantte** [comment]
Yes, but in this case this implementation is necessary for the correct implementation of the user management logic with the support of ASP.NET Identity (At least this was the best solution I found). Furthermore, it can be justified by saying that the class ArmoryUser inherits from is part of the ASP.NET Identity library domain.

**Comment by afgalvan** [comment]
Ok, thanks for the clarification, I'll close the issue
